### ISSUE TITLE
Custom Welcome Message

### ISSUE THREAD

**Issue by kelsie-c** [kelsie-c/Highgarden_HighBot#2]
When a new user joins the server, send a custom embedded message with instructions to the welcome channel. 

### Use Cases:
AS A server manager
I WANT TO restrict new joiners to the welcome channel and provide them with specific instructions
SO THAT new joiners don't have full access until the approval process is complete.

AS A server manager
I WANT TO receive a simple form to reject or accept new server applicants
SO THAT the process of adding new members is faster.

### Steps:
1. User joins Discord server from an invite
2. Assign a new joiner role to user
3. Give access to pre-server channel
4. Auto-generate a message from HighBot to welcome user & provide instructions
5. (possible) Ask user if they have filled out application form
6. (possible) If step 5 = no, populate form in modal for user to fill out and send responses to application form, then notify server manager of complete application
7. (possible) If step 5 = yes, notify server manager of complete application

Stretch goal 1: send direct message to server manager for approval.
Stretch goal 2: capture response from server manager and either 1) send rejection message and ban, or 2) add roles to accepted user based on input.

### Tasks
- [ ] Pre-server channel
- [ ] Single-user message view
- [ ] Forms & modals
- [ ] Capture user response in DM
- [ ] Assigning roles

See attached image for sample welcome message.

![Image](https://user-images.githubusercontent.com/76745890/181823776-5a496465-197e-41ce-a303-f873e5875fc7.png)
