### ISSUE TITLE
serious-coffee Monitor

### ISSUE THREAD

**Issue by kelsie-c** [kelsie-c/Highgarden_HighBot#7]
Monitor the serious-coffee chat to prevent lurkers.

### Use Cases

AS A server manager
I WANT TO use HighBot to monitor serious-coffee to track usage
SO THAT the channel's safety can be maintained by preventing lurking.

### Steps

1. Once daily, get the list of users with the serious-coffee role. 
2. Check the new list against the list from the previous day, adding new users to the list and removing users that no longer have the role.
3. When adding new users to the list, also add the first date they were found to have the serious-coffee role plus three weeks. 
4. Duplicate list to create new list and remove users from the list that have immunity.
5. Remove any users that do not have the current date.
6. For each member in the list, find the date of their last message in the serious-coffee channel. If date of last message is more than 3 weeks before current date, find the difference in days and add that number to the list. If date of last message is less than 3 weeks, remove from new list and update old list date to be date of last message plus three weeks.
7. Send list of users with the number of days since their last message to server manager for final approval before being removed. Ideally, this would be a modal that would give a "yes" or "no" option to choose from next to each user's name. 
8. Users that the server manager elects to remove will lose the serious-coffee role and their reaction to the serious-coffee role will be removed from self-assign-roles.

Possible solution: Instead of a DM to server manager, list of users requiring approval can be sent to a private channel where a few people with access could provide the necessary approval to allow the server manager the ability to delegate this task.

### Tasks

- [ ] Get list of channel users
- [ ] Find date of last message by specific user
- [ ] Send users to server manager in a simple way 
- [ ] Sending buttons in a message
